### ISSUE TITLE
Protocol error (Target.detachFromTarget): No session with given id

### ISSUE THREAD

**Issue by hamletbatista** [ranksense/url-inspector-automator#1]
Future exception was never retrieved
future: <Future finished exception=NetworkError('Protocol error (Target.detachFromTarget): No session with given id')>
pyppeteer.errors.NetworkError: Protocol error (Target.detachFromTarget): No session with given id
Resetting GSC Home to new site: https://www.xxxx.com
Traceback (most recent call last):
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/execution_context.py", line 86, in evaluateHandle
    'userGesture': True,
pyppeteer.errors.NetworkError: Protocol error (Runtime.evaluate): Cannot find context with specified id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "url_inspector_automator.py", line 221, in inspectURLs
    self.results = asyncio.get_event_loop().run_until_complete(self.auto.inspect_urls(urls, criteria, action, delay, action_delay))
  File "/Users/hamletbatista/miniconda3/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/Users/hamletbatista/Development/url_inspection_tool/chrome_automator.py", line 54, in inspect_urls
    data = await self.inspect_url(url, delay) #, submit, criteria))
  File "/Users/hamletbatista/Development/url_inspection_tool/chrome_automator.py", line 109, in inspect_url
    await self.page.click(sel)
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/page.py", line 1507, in click
    await frame.click(selector, options, **kwargs)
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/frame_manager.py", line 567, in click
    handle = await self.J(selector)
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/frame_manager.py", line 302, in querySelector
    document = await self._document()
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/frame_manager.py", line 312, in _document
    document = (await context.evaluateHandle('document')).asElement()
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/execution_context.py", line 89, in evaluateHandle
    _rewriteError(e)
  File "/Users/hamletbatista/miniconda3/lib/python3.7/site-packages/pyppeteer/execution_context.py", line 238, in _rewriteError
    raise type(error)(msg)
pyppeteer.errors.NetworkError: Execution context was destroyed, most likely because of a navigation.
Abort trap: 6

**Comment by hamletbatista** [comment]
I found this issue only but no comments or solution https://github.com/miyakogi/pyppeteer/issues/194

I started the app again and no problems.
