### ISSUE TITLE
KeyError: "EXTRACTION"

### ISSUE THREAD

**Issue by pku-impact** [ranksense/url-inspector-automator#5]
I am trying to run the script on a windows, anaconda prompt, but receiving this error: 

Selectors loaded
Traceback (most recent call last):
  File "C:\Users\PKU\Documents\url-inspector-automator-master\url_inspector_automator.py", line 270, in <module>
    window = URLInspector()
  File "C:\Users\PKU\Documents\url-inspector-automator-master\url_inspector_automator.py", line 51, in __init__
    self.generate_javascript_files()
  File "C:\Users\PKU\Documents\url-inspector-automator-master\url_inspector_automator.py", line 118, in generate_javascript_files
    self.extraction_fn = template.render(settings=self.config['EXTRACTION'])
  File "C:\Users\PKU\AppData\Local\Continuum\anaconda3\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'EXTRACTION'

Something with the script. Is this something you can help me with?

**Comment by hamletbatista** [comment]
@pku-impact can you check your file selectors.ini and see if that section is there? It seems it isn't. 

Unfortunately, I don't use Windows. Maybe @jlhernando can tell you how he got it to work in Windows.
